routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::get('profile', 'UserController@profile');
Route::post('profile', 'UserController@update_avatar');
Route::resource('files' ,'FileController');
Route::get('files/{uuid}/show', 'FileController@show')->name('files.show');
Route::get('files/{uuid}/download', 'FileController@download')->name('files.download');
Route::get('files/{uuid}/delete', 'FileController@delete')->name('files.delete');
Route::get('files/created','FileController@created');

app/File.php
<?php


namespace App;


use Illuminate\Database\Eloquent\Model;

class File extends Model
{
    
    protected $fillable = ['uuid', 'title', 'cover','userid','hasPassword'];

}

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/FileController.php
<?php


namespace App\Http\Controllers;

use App\File;
use App\User;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Storage;
use Webpatser\Uuid\Uuid;
use Illuminate\Support\Facades\Auth;

class FileController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth');
    }

    public function index()
    {
        $user = Auth::user();
        $files = File::all();
        return view('files.index', compact('files'), compact('user'));
    }

    public function create()
    {
        return view('files.upload');
    }

    public function created()
    {
        $user = Auth::user();
        $files = File::with(function ($query) use ($user) {
            $query->where('userid', $user->id);
        });
        return view('file.created', compact($files));
    }

    public function store(Request $request)
    {
        $request->validate([
            'cover' => 'required|image|mimes:jpeg,png,jpg,gif,svg|max:2048',
        ]);
        $file = $request->all();
        $file['uuid'] = (string)Uuid::generate();
        if ($request->hasFile('cover')) {
            $file['cover'] = $file['uuid'] . "_" . $request->cover->getClientOriginalName();
            $request->cover->storeAs('files', $file['cover'], 'uploads');
        } else {
            return view('files.notcreated')->with('msg', 'فایلی مشخص نشده است!');
        }
        if (!$request->has('title')) {
            $file['title'] = $request->cover->getClientOriginalName();
        }
        $file['userid'] = Auth::user()->id;
        $file['hasPassword'] = false;
        $createdFile = File::create($file);
        return view('files.created')->with('file', $createdFile);
    }

    public function download($uuid)
    {
        $file = File::where('uuid', $uuid)->firstOrFail();
        $pathToFile = storage_path('app/files/' . $file->cover);
        return response()->download($pathToFile);
    }

    public function show($uuid)
    {
        $file = File::where('uuid', $uuid)->firstOrFail();
        $user = User::where('id', $file->userid)->firstOrFail();
        return view('files.show')->with('file', $file)->with('user', $user);
    }

    public function delete($uuid)
    {
        $file = File::where('uuid', $uuid)->firstOrFail();
        $fileUser = User::where('id', $file->userid)->firstOrFail();
        $thisUser = Auth::user();
        $msg = 'فایل '.$file->title .' پاک شد!';

        if($fileUser->id == $thisUser->id){
            $file->delete();
        }else{
            return view('files.delete')->with('error', 'فایل متعلق به شما نیست!');
        }
        return back()->with('success',$msg);
    }

}

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use App\File;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;

class HomeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Contracts\Support\Renderable
     */
    public function index()
    {
        $userid=Auth::user()->id;
        $files=File::all()->where('userid',$userid);
        return view('home',compact('files',$files));
    }
}

app/Http/Controllers/UserController.php
<?php


namespace App\Http\Controllers;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;

class UserController
{
    public function profile()
    {
        $user = Auth::user();
        return view('profile', compact('user', $user));
    }

    public function update_avatar(Request $request)
    {

        $request->validate([
            'avatar' => 'required|image|mimes:jpeg,png,jpg,gif,svg|max:2048',
        ]);

        $user = Auth::user();

        $avatarName = $user->id . '_avatar' . time() . '.' . request()->avatar->getClientOriginalExtension();

        $request->avatar->storeAs('avatars', $avatarName);

        $user->avatar = $avatarName;
        $user->save();

        return back()
            ->with('success', 'نمایه کابری شما با موفقیت تعویض شد.');

    }

}

resources/views/files/created.blade.php
@extends('layouts.app')
@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-8">
                <div class="card">
                    <div class="card-header beshkaste" style="font-size: 3rem">
                        <i class="far fa-file-alt" style="font-size: 1rem"></i>
                        فایل
                        <span class="fileName samim">
                            {{ $file->title }}
                        </span>
                        ساخته شد
                    </div>

                    <div class="card-body samim">
                        شما میتوانید با

                        <a href="files/{{ $file->uuid  }}/show">این آدرس</a>
                        به این فایل دسترسی داشته باشید.
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/files/delete.blade.php
@extends('layouts.app')
@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-8">
                <div class="card">
                    @if(isset($error))
                        <div class="card-header beshkaste justify-content-center text-center" style="font-size: 3rem">
                            <i class="fas fa-angry"></i>
                            <h1 style="font-size: 4rem">ای بابا ...</h1>
                        </div>

                        <div class="card-body samim text-center">
                            {{ error }}
                        </div>
                    @endif

                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/files/index.blade.php
@extends('layouts.app')
@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-8">
                <div class="card">
                    <div class="card-header">Dashboard</div>

                    <div class="card-body">
                        something
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/files/notcreated.blade.php
@extends('layouts.app')
@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-8">
                <div class="card">
                    <div class="card-header beshkaste" style="font-size: 3rem">
                        <i class="far fa-file-alt" style="font-size: 1rem; color: red;"></i>
                        فایل
                        ساخته نشد
                    </div>

                    <div class="card-body samim">
                        {{ $msg }}
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/files/show.blade.php
@extends('layouts.app')
@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-8">
                <div class="card">
                    <div class="card-header beshkaste" style="font-size: 3rem">
                        <div class="row justify-content-center">
                            <img class="rounded-circle" src="/storage/avatars/{{ $user->avatar }}" height="150"
                                 width="150" style="position: relative;right: 14px;"/>
                            <i class="fas fa-share" id="shareIcon"></i>
                        </div>
                        <div class="=justify-content-center text-center">
                            <span class="userName samim" style="max-width: 100%">
                                <i class="fas fa-user"></i>
                                {{ $user->name }}
                            </span>
                        </div>
                        <div class="=justify-content-center text-center">
                            <span class="fileName samim" style="max-width: 100%;line-height: 2rem">
                            <i class="far fa-file-alt" style="font-size: 1rem;"></i>
                                {{ $file->title }}
                            </span>
                        </div>

                    </div>

                    <div class="card-body samim text-center">
                        شما میتوانید با

                        <a href="../{{ $file->uuid  }}/download">این آدرس</a>
                        به این فایل دسترسی داشته باشید.
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/files/upload.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-8">
                <div class="card">
                    <div class="card-header beshkaste text-center" style="font-size: 4rem" >آپلود فایل جدید</div>

                    <div class="card-body samim">

                        <form action="{{ route('files.store') }}" method="POST" enctype="multipart/form-data">
                            @csrf

                            عنوان فایل:
                            <br>
                            <input type="text" name="title" class="form-control">

                            <br>

                            فایل:
                            <br>
                            <style>

                                /****** CODE ******/

                                .file-upload{display:block;text-align:center;font-family: Helvetica, Arial, sans-serif;font-size: 12px;}
                                .file-upload .file-select{display:block;border: 2px solid #dce4ec;border-radius: 4px;color: #34495e;cursor:pointer;height:40px;line-height:40px;text-align:left;background:#FFFFFF;overflow:hidden;position:relative;}
                                .file-upload .file-select .file-select-button{background:#dce4ec;padding:0 10px;display:inline-block;height:40px;line-height:40px;}
                                .file-upload .file-select .file-select-name{line-height:40px;display:inline-block;padding:0 10px;}
                                .file-upload .file-select:hover{border-color:#34495e;transition:all .2s ease-in-out;-moz-transition:all .2s ease-in-out;-webkit-transition:all .2s ease-in-out;-o-transition:all .2s ease-in-out;}
                                .file-upload .file-select:hover .file-select-button{background:#34495e;color:#FFFFFF;transition:all .2s ease-in-out;-moz-transition:all .2s ease-in-out;-webkit-transition:all .2s ease-in-out;-o-transition:all .2s ease-in-out;}
                                .file-upload.active .file-select{border-color:#3fa46a;transition:all .2s ease-in-out;-moz-transition:all .2s ease-in-out;-webkit-transition:all .2s ease-in-out;-o-transition:all .2s ease-in-out;}
                                .file-upload.active .file-select .file-select-button{background:#3fa46a;color:#FFFFFF;transition:all .2s ease-in-out;-moz-transition:all .2s ease-in-out;-webkit-transition:all .2s ease-in-out;-o-transition:all .2s ease-in-out;}
                                .file-upload .file-select input[type=file]{z-index:100;cursor:pointer;position:absolute;height:100%;width:100%;top:0;left:0;opacity:0;filter:alpha(opacity=0);}
                                .file-upload .file-select.file-select-disabled{opacity:0.65;}
                                .file-upload .file-select.file-select-disabled:hover{cursor:default;display:block;border: 2px solid #dce4ec;color: #34495e;cursor:pointer;height:40px;line-height:40px;margin-top:5px;text-align:left;background:#FFFFFF;overflow:hidden;position:relative;}
                                .file-upload .file-select.file-select-disabled:hover .file-select-button{background:#dce4ec;color:#666666;padding:0 10px;display:inline-block;height:40px;line-height:40px;}
                                .file-upload .file-select.file-select-disabled:hover .file-select-name{line-height:40px;display:inline-block;padding:0 10px;}
                            </style>

                            <div class="file-upload mt-3 samim" style="direction: ltr">
                                <div class="file-select">
                                    <div class="file-select-button" id="fileName">انتخاب فایل</div>
                                    <div class="file-select-name" id="noFile">هیچ فایلی انتخاب نشده است</div>
                                    <input type="file" name="cover" aria-describedby="fileHelp" id="avatarFile">
                                </div>
                            </div>
                            <script>
                                $('#avatarFile').bind('change', function () {
                                    var filename = $("#avatarFile").val();
                                    if (/^\s*$/.test(filename)) {
                                        $(".file-upload").removeClass('active');
                                        $("#noFile").text("فایلی انتخاب نشده...");
                                    }
                                    else {
                                        $(".file-upload").addClass('active');
                                        $("#noFile").text(filename.replace("C:\\fakepath\\", ""));
                                    }
                                });
                            </script>

                            <br>
                            <input type="checkbox" name="hasPassword">
                            پسورد داره؟
                            <br><br>

                            <input type="submit" value="آپلود فایل" class="btn btn-primary">

                        </form>

                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-8 justify-content-center text-center">

                @if ($message = Session::get('success'))

                    <div class="alert alert-success alert-block">

                        <button type="button" class="close" data-dismiss="alert">×</button>

                        <strong class="pr-2">{{ $message }}</strong>

                    </div>

                @endif

                <div class="row">
                    <a href="/files/create" class="btn btn-block btn-outline-light m-3 samim" style="font-size: 1.3rem">فایل
                        جدید ؟</a>
                </div>
                <div class="card">
                    <div class="card-header text-center beshkaste" style="font-size: 3rem">فایل‌های من</div>

                    <div class="card-body samim">
                        @if (session('status'))
                            <div class="alert alert-success" role="alert">
                                {{ session('status') }}
                            </div>
                        @endif
                        @foreach($files as $file)
                            <div class="card">
                                <div class="row">
                                    <button class="btn btn-dark d-inline-block">
                                        <i class="far fa-file-alt" style="font-size: 1rem;"></i>

                                        {{ $file->title }}
                                    </button>
                                    <a href="/files/{{ $file->uuid }}/delete" class="mr-auto btn btn-outline-danger"><i
                                                class="fas fa-trash"></i></a>

                                    <a href="/files/{{ $file->uuid }}/show" class="btn mr-2 btn-primary"><i
                                                class="far fa-eye"></i></a>
                                </div>
                            </div>
                        @endforeach
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}"></script>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet">

    <!-- Styles -->
    <script src="https://kit.fontawesome.com/f72adb371d.js"></script>
    <link href="{{ asset('css/font.css') }}" rel="stylesheet">
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">

</head>
<body>
<div id="app">
    <nav class="navbar navbar-expand-md navbar-dark bg-dark shadow-sm">
        <div class="container">
            <a class="navbar-brand" href="{{ url('/') }}">
                <div class="logo flicker-1">
                    <i class="fas fa-cloud-upload-alt"></i>
                    <span class="logo-text">پایکر فایل</span>
                </div>
            </a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
                    aria-controls="navbarSupportedContent" aria-expanded="false"
                    aria-label="{{ __('Toggle navigation') }}">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <!-- Left Side Of Navbar -->
                <ul class="navbar-nav mr-auto">

                </ul>

                <!-- Right Side Of Navbar -->
                <ul class="navbar-nav mr-auto" >
                    <!-- Authentication Links -->
                    @guest
                        <li class="nav-item" id="login">
                            <a class="nav-link beshkaste" href="{{ route('login') }}"
                               style="line-height: 1rem;font-size: 3rem;top: -0.5rem;position: relative;">ورود</a>
                        </li>
                        @if (Route::has('register'))
                            <li class="nav-item " id="signup">
                                <a class="nav-link beshkaste " href="{{ route('register') }}"
                                   style="line-height: 1rem;font-size: 3rem;top: -0.5rem;position: relative;">ثبت‌نام</a>
                            </li>
                        @endif
                    @else
                        <li class="nav-item dropdown">
                            <a id="navbarDropdown" class="nav-link dropdown-toggle samim" href="#" role="button"
                               data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                {{ Auth::user()->name }} <span class="caret"></span>
                            </a>

                            <div class="dropdown-menu dropdown-menu-left" aria-labelledby="navbarDropdown">
                                <a class="dropdown-item text-center samim" href="/home">
                                    فایل‌های من
                                </a>
                                <a class="dropdown-item text-center samim" href="/files/create">
                                    آپلود فایل جدید
                                </a>
                                <a class="dropdown-item text-center samim" href="/profile">
                                    صفحه کاربری
                                </a>
                                <a class="dropdown-item text-center samim" href="{{ route('logout') }}"
                                   onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                    خروج
                                </a>

                                <form id="logout-form" action="{{ route('logout') }}" method="POST"
                                      style="display: none;">
                                    @csrf
                                </form>
                            </div>
                        </li>
                    @endguest
                </ul>
            </div>
        </div>
    </nav>

    <main class="py-4">
        @yield('content')
    </main>
</div>
</body>
</html>

resources/views/profile.blade.php
@extends('layouts.app')

@section('content')
    <link rel="stylesheet" href="{{asset('css/cropper.css')}}">
    <script src="{{assert('js/cropper.js')}}"></script>
    <div class="container samim">
        <div class="row">
            <div class="col-12">
                @if ($message = Session::get('success'))

                    <div class="alert alert-success alert-block">

                        <button type="button" class="close" data-dismiss="alert">×</button>

                        <strong class="pr-2">{{ $message }}</strong>

                    </div>

                @endif

                @if (count($errors) > 0)
                    <div class="alert alert-danger">
                        <button type="button" class="close pl-2" data-dismiss="alert">×</button>
                        <strong>اوپس !</strong> هنگام عوض کردن نمایه کاربری اشکالی رخ داده است.<br><br>
                        <ul>
                            @foreach ($errors->all() as $error)
                                <li>{{ $error }}</li>
                            @endforeach
                        </ul>
                    </div>
                @endif
            </div>
        </div>
    </div>
    <div class="container pt-5 pb-5">
        <div class="row justify-content-center">
            <div class="col-lg-5 col-md-8 card pt-5 pb-5">
                <div class="row justify-content-center">
                    <style>
                        .name{
                            font-size: 3rem;
                            text-align: center;
                            display: block;
                            margin-bottom: 28px;
                            background-color: #343438;
                            color: white;
                            border-radius: 4px;
                            width: 80%;

                        }
                    </style>
                    <div class="name" >
                        <span class="label label-default rank-label samim">{{$user->name}}</span>
                    </div>

                    <div class="profile-header-container">
                        <div class="profile-header-img">
                            <img class="rounded-circle" src="/storage/avatars/{{ $user->avatar }}" height="300"
                                 width="300"/>
                            <small id="fileHelp" class="form-text text-muted">این عکس نمایه کاربری شماست که کاربران دیگر
                                مشاهده
                                میکنند.
                            </small>
                            <!-- badge -->
                            <div class="rank-label-container">
                            </div>
                        </div>
                    </div>

                </div>
                <div class="row justify-content-center text-center">
                    <form action="/profile" method="post" enctype="multipart/form-data">
                        @csrf
                        <style>

                            /****** CODE ******/

                            .file-upload{display:block;text-align:center;font-family: Helvetica, Arial, sans-serif;font-size: 12px;}
                            .file-upload .file-select{display:block;border: 2px solid #dce4ec;border-radius: 4px;color: #34495e;cursor:pointer;height:40px;line-height:40px;text-align:left;background:#FFFFFF;overflow:hidden;position:relative;}
                            .file-upload .file-select .file-select-button{background:#dce4ec;padding:0 10px;display:inline-block;height:40px;line-height:40px;}
                            .file-upload .file-select .file-select-name{line-height:40px;display:inline-block;padding:0 10px;}
                            .file-upload .file-select:hover{border-color:#34495e;transition:all .2s ease-in-out;-moz-transition:all .2s ease-in-out;-webkit-transition:all .2s ease-in-out;-o-transition:all .2s ease-in-out;}
                            .file-upload .file-select:hover .file-select-button{background:#34495e;color:#FFFFFF;transition:all .2s ease-in-out;-moz-transition:all .2s ease-in-out;-webkit-transition:all .2s ease-in-out;-o-transition:all .2s ease-in-out;}
                            .file-upload.active .file-select{border-color:#3fa46a;transition:all .2s ease-in-out;-moz-transition:all .2s ease-in-out;-webkit-transition:all .2s ease-in-out;-o-transition:all .2s ease-in-out;}
                            .file-upload.active .file-select .file-select-button{background:#3fa46a;color:#FFFFFF;transition:all .2s ease-in-out;-moz-transition:all .2s ease-in-out;-webkit-transition:all .2s ease-in-out;-o-transition:all .2s ease-in-out;}
                            .file-upload .file-select input[type=file]{z-index:100;cursor:pointer;position:absolute;height:100%;width:100%;top:0;left:0;opacity:0;filter:alpha(opacity=0);}
                            .file-upload .file-select.file-select-disabled{opacity:0.65;}
                            .file-upload .file-select.file-select-disabled:hover{cursor:default;display:block;border: 2px solid #dce4ec;color: #34495e;cursor:pointer;height:40px;line-height:40px;margin-top:5px;text-align:left;background:#FFFFFF;overflow:hidden;position:relative;}
                            .file-upload .file-select.file-select-disabled:hover .file-select-button{background:#dce4ec;color:#666666;padding:0 10px;display:inline-block;height:40px;line-height:40px;}
                            .file-upload .file-select.file-select-disabled:hover .file-select-name{line-height:40px;display:inline-block;padding:0 10px;}
                        </style>

                        <div class="file-upload mt-3 samim" style="direction: ltr">
                            <div class="file-select">
                                <div class="file-select-button" id="fileName">انتخاب فایل</div>
                                <div class="file-select-name" id="noFile">هیچ فایلی انتخاب نشده است</div>
                                <input type="file" name="avatar" aria-describedby="fileHelp" id="avatarFile">
                            </div>
                        </div>
                        <script>
                            $('#avatarFile').bind('change', function () {
                                var filename = $("#avatarFile").val();
                                if (/^\s*$/.test(filename)) {
                                    $(".file-upload").removeClass('active');
                                    $("#noFile").text("فایلی انتخاب نشده...");
                                }
                                else {
                                    $(".file-upload").addClass('active');
                                    $("#noFile").text(filename.replace("C:\\fakepath\\", ""));
                                }
                            });
                        </script>

                        <button type="submit" class="btn btn-primary samim mt-3">انجام تغییرات</button>
                    </form>
                </div>
            </div>
        </div>

    </div>
@endsection